// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ovh

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	ovhtypes "github.com/ovh/terraform-provider-ovh/ovh/types"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OkmsServiceKeysDataSourceSchema(ctx context.Context) schema.Schema {
	attrs := map[string]schema.Attribute{
		"okms_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Okms ID",
			MarkdownDescription: "Okms ID",
		},
		"okms_service_keys": schema.SetNestedAttribute{
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "Creation time of the key",
						MarkdownDescription: "Creation time of the key",
					},
					"curve": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "Curve type for Elliptic Curve (EC) keys",
						MarkdownDescription: "Curve type for Elliptic Curve (EC) keys",
					},
					"id": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "Key ID",
						MarkdownDescription: "Key ID",
					},
					"keys": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"alg": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "The algorithm intended to be used with the key",
									MarkdownDescription: "The algorithm intended to be used with the key",
								},
								"crv": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "The cryptographic curve used with the key",
									MarkdownDescription: "The cryptographic curve used with the key",
								},
								"d": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Sensitive:           true,
									Description:         "The RSA or EC private exponent",
									MarkdownDescription: "The RSA or EC private exponent",
								},
								"dp": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Sensitive:           true,
									Description:         "The RSA private key's first factor CRT exponent",
									MarkdownDescription: "The RSA private key's first factor CRT exponent",
								},
								"dq": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Sensitive:           true,
									Description:         "The RSA private key's second factor CRT exponent",
									MarkdownDescription: "The RSA private key's second factor CRT exponent",
								},
								"e": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "The exponent value for the RSA public key",
									MarkdownDescription: "The exponent value for the RSA public key",
								},
								"k": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Sensitive:           true,
									Description:         "The value of the symmetric (or other single-valued) key",
									MarkdownDescription: "The value of the symmetric (or other single-valued) key",
								},
								"key_ops": schema.ListAttribute{
									CustomType:          ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
									Computed:            true,
									Description:         "The operation for which the key is intended to be used",
									MarkdownDescription: "The operation for which the key is intended to be used",
								},
								"kid": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "key ID parameter used to match a specific key",
									MarkdownDescription: "key ID parameter used to match a specific key",
								},
								"kty": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "Key type parameter identifies the cryptographic algorithm family used with the key, such as RSA or EC",
									MarkdownDescription: "Key type parameter identifies the cryptographic algorithm family used with the key, such as RSA or EC",
								},
								"n": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "The modulus value for the RSA public key",
									MarkdownDescription: "The modulus value for the RSA public key",
								},
								"p": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Sensitive:           true,
									Description:         "The first prime factor of the RSA private key",
									MarkdownDescription: "The first prime factor of the RSA private key",
								},
								"q": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Sensitive:           true,
									Description:         "The second prime factor of the RSA private key",
									MarkdownDescription: "The second prime factor of the RSA private key",
								},
								"qi": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Sensitive:           true,
									Description:         "The CRT coefficient of the second factor of the RSA private key",
									MarkdownDescription: "The CRT coefficient of the second factor of the RSA private key",
								},
								"use": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "The intended use of the public key",
									MarkdownDescription: "The intended use of the public key",
								},
								"x": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "The x coordinate for the Elliptic Curve point",
									MarkdownDescription: "The x coordinate for the Elliptic Curve point",
								},
								"y": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "The y coordinate for the Elliptic Curve point",
									MarkdownDescription: "The y coordinate for the Elliptic Curve point",
								},
							},
							CustomType: OkmsServiceKeysKeysType{
								ObjectType: types.ObjectType{
									AttrTypes: OkmsServiceKeysKeysValue{}.AttributeTypes(ctx),
								},
							},
						},
						CustomType:          ovhtypes.NewTfListNestedType[OkmsServiceKeysKeysValue](ctx),
						Computed:            true,
						Description:         "The key in JWK format",
						MarkdownDescription: "The key in JWK format",
					},
					"name": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "Key name",
						MarkdownDescription: "Key name",
					},
					"operations": schema.ListAttribute{
						CustomType:          ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
						Computed:            true,
						Description:         "The operations for which the key is intended to be used",
						MarkdownDescription: "The operations for which the key is intended to be used",
					},
					"size": schema.Int64Attribute{
						CustomType:          ovhtypes.TfInt64Type{},
						Computed:            true,
						Description:         "Size of the key",
						MarkdownDescription: "Size of the key",
					},
					"state": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "State of the key",
						MarkdownDescription: "State of the key",
					},
					"type": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "Key type",
						MarkdownDescription: "Key type",
					},
				},
				CustomType: OkmsServiceKeysType{
					ObjectType: types.ObjectType{
						AttrTypes: OkmsServiceKeysValue{}.AttributeTypes(ctx),
					},
				},
			},
			CustomType: ovhtypes.NewTfListNestedType[OkmsServiceKeysValue](ctx),
			Computed:   true,
		},
	}

	return schema.Schema{
		Attributes: attrs,
	}
}

type OkmsServiceKeysModel struct {
	OkmsId          ovhtypes.TfStringValue                           `tfsdk:"okms_id" json:"okmsId"`
	OkmsServiceKeys ovhtypes.TfListNestedValue[OkmsServiceKeysValue] `tfsdk:"okms_service_keys" json:"okmsServiceKeys"`
}

func (v *OkmsServiceKeysModel) MergeWith(other *OkmsServiceKeysModel) {

	if (v.OkmsId.IsUnknown() || v.OkmsId.IsNull()) && !other.OkmsId.IsUnknown() {
		v.OkmsId = other.OkmsId
	}

	if (v.OkmsServiceKeys.IsUnknown() || v.OkmsServiceKeys.IsNull()) && !other.OkmsServiceKeys.IsUnknown() {
		v.OkmsServiceKeys = other.OkmsServiceKeys
	}

}
	




var _ basetypes.ObjectTypable = OkmsServiceKeysType{}

type OkmsServiceKeysType struct {
	basetypes.ObjectType
}

func (t OkmsServiceKeysType) Equal(o attr.Type) bool {
	other, ok := o.(OkmsServiceKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OkmsServiceKeysType) String() string {
	return "OkmsServiceKeysType"
}

func (t OkmsServiceKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be ovhtypes.TfStringValue, was: %T`, createdAtAttribute))
	}

	curveAttribute, ok := attributes["curve"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`curve is missing from object`)

		return nil, diags
	}

	curveVal, ok := curveAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`curve expected to be ovhtypes.TfStringValue, was: %T`, curveAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be ovhtypes.TfStringValue, was: %T`, idAttribute))
	}

	keysAttribute, ok := attributes["keys"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`keys is missing from object`)

		return nil, diags
	}

	keysVal, ok := keysAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`keys expected to be basetypes.ListValue, was: %T`, keysAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be ovhtypes.TfStringValue, was: %T`, nameAttribute))
	}

	operationsAttribute, ok := attributes["operations"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`operations is missing from object`)

		return nil, diags
	}

	operationsVal, ok := operationsAttribute.(ovhtypes.TfListNestedValue[ovhtypes.TfStringValue])

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`operations expected to be ovhtypes.TfListNestedValue[ovhtypes.TfStringValue], was: %T`, operationsAttribute))
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return nil, diags
	}

	sizeVal, ok := sizeAttribute.(ovhtypes.TfInt64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be ovhtypes.TfInt64Value, was: %T`, sizeAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be ovhtypes.TfStringValue, was: %T`, stateAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be ovhtypes.TfStringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OkmsServiceKeysValue{
		CreatedAt:           createdAtVal,
		Curve:               curveVal,
		Id:                  idVal,
		Keys:                keysVal,
		Name:                nameVal,
		Operations:          operationsVal,
		Size:                sizeVal,
		State:               stateVal,
		OkmsServiceKeysType: typeVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewOkmsServiceKeysValueNull() OkmsServiceKeysValue {
	return OkmsServiceKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewOkmsServiceKeysValueUnknown() OkmsServiceKeysValue {
	return OkmsServiceKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOkmsServiceKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OkmsServiceKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OkmsServiceKeysValue Attribute Value",
				"While creating a OkmsServiceKeysValue value, a missing attribute value was detected. "+
					"A OkmsServiceKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OkmsServiceKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OkmsServiceKeysValue Attribute Type",
				"While creating a OkmsServiceKeysValue value, an invalid attribute value was detected. "+
					"A OkmsServiceKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OkmsServiceKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OkmsServiceKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OkmsServiceKeysValue Attribute Value",
				"While creating a OkmsServiceKeysValue value, an extra attribute value was detected. "+
					"A OkmsServiceKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OkmsServiceKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOkmsServiceKeysValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be ovhtypes.TfStringValue, was: %T`, createdAtAttribute))
	}

	curveAttribute, ok := attributes["curve"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`curve is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	curveVal, ok := curveAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`curve expected to be ovhtypes.TfStringValue, was: %T`, curveAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	idVal, ok := idAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be ovhtypes.TfStringValue, was: %T`, idAttribute))
	}

	keysAttribute, ok := attributes["keys"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`keys is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	keysVal, ok := keysAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`keys expected to be basetypes.ListValue, was: %T`, keysAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be ovhtypes.TfStringValue, was: %T`, nameAttribute))
	}

	operationsAttribute, ok := attributes["operations"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`operations is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	operationsVal, ok := operationsAttribute.(ovhtypes.TfListNestedValue[ovhtypes.TfStringValue])

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`operations expected to be ovhtypes.TfListNestedValue[ovhtypes.TfStringValue], was: %T`, operationsAttribute))
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	sizeVal, ok := sizeAttribute.(ovhtypes.TfInt64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be ovhtypes.TfInt64Value, was: %T`, sizeAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be ovhtypes.TfStringValue, was: %T`, stateAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewOkmsServiceKeysValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be ovhtypes.TfStringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewOkmsServiceKeysValueUnknown(), diags
	}

	return OkmsServiceKeysValue{
		CreatedAt:           createdAtVal,
		Curve:               curveVal,
		Id:                  idVal,
		Keys:                keysVal,
		Name:                nameVal,
		Operations:          operationsVal,
		Size:                sizeVal,
		State:               stateVal,
		OkmsServiceKeysType: typeVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewOkmsServiceKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OkmsServiceKeysValue {
	object, diags := NewOkmsServiceKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOkmsServiceKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OkmsServiceKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOkmsServiceKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOkmsServiceKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOkmsServiceKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOkmsServiceKeysValueMust(OkmsServiceKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OkmsServiceKeysType) ValueType(ctx context.Context) attr.Value {
	return OkmsServiceKeysValue{}
}

var _ basetypes.ObjectValuable = OkmsServiceKeysValue{}

type OkmsServiceKeysValue struct {
	CreatedAt           ovhtypes.TfStringValue                               `tfsdk:"created_at" json:"createdAt"`
	Curve               ovhtypes.TfStringValue                               `tfsdk:"curve" json:"curve"`
	Id                  ovhtypes.TfStringValue                               `tfsdk:"id" json:"id"`
	Keys                ovhtypes.TfListNestedValue[OkmsServiceKeysKeysValue] `tfsdk:"keys" json:"keys"`
	Name                ovhtypes.TfStringValue                               `tfsdk:"name" json:"name"`
	Operations          ovhtypes.TfListNestedValue[ovhtypes.TfStringValue]   `tfsdk:"operations" json:"operations"`
	Size                ovhtypes.TfInt64Value                                `tfsdk:"size" json:"size"`
	State               ovhtypes.TfStringValue                               `tfsdk:"state" json:"state"`
	OkmsServiceKeysType ovhtypes.TfStringValue                               `tfsdk:"type" json:"type"`
	state               attr.ValueState
}

func (v *OkmsServiceKeysValue) UnmarshalJSON(data []byte) error {
	type JsonOkmsServiceKeysValue OkmsServiceKeysValue

	var tmp JsonOkmsServiceKeysValue
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}
	v.CreatedAt = tmp.CreatedAt
	v.Curve = tmp.Curve
	v.Id = tmp.Id
	v.Keys = tmp.Keys
	v.Name = tmp.Name
	v.Operations = tmp.Operations
	v.Size = tmp.Size
	v.State = tmp.State
	v.OkmsServiceKeysType = tmp.OkmsServiceKeysType

	v.state = attr.ValueStateKnown

	return nil
}

func (v *OkmsServiceKeysValue) MergeWith(other *OkmsServiceKeysValue) {

	if (v.CreatedAt.IsUnknown() || v.CreatedAt.IsNull()) && !other.CreatedAt.IsUnknown() {
		v.CreatedAt = other.CreatedAt
	}

	if (v.Curve.IsUnknown() || v.Curve.IsNull()) && !other.Curve.IsUnknown() {
		v.Curve = other.Curve
	}

	if (v.Id.IsUnknown() || v.Id.IsNull()) && !other.Id.IsUnknown() {
		v.Id = other.Id
	}

	if (v.Keys.IsUnknown() || v.Keys.IsNull()) && !other.Keys.IsUnknown() {
		v.Keys = other.Keys
	}

	if (v.Name.IsUnknown() || v.Name.IsNull()) && !other.Name.IsUnknown() {
		v.Name = other.Name
	}

	if (v.Operations.IsUnknown() || v.Operations.IsNull()) && !other.Operations.IsUnknown() {
		v.Operations = other.Operations
	}

	if (v.Size.IsUnknown() || v.Size.IsNull()) && !other.Size.IsUnknown() {
		v.Size = other.Size
	}

	if (v.State.IsUnknown() || v.State.IsNull()) && !other.State.IsUnknown() {
		v.State = other.State
	}

	if (v.OkmsServiceKeysType.IsUnknown() || v.OkmsServiceKeysType.IsNull()) && !other.OkmsServiceKeysType.IsUnknown() {
		v.OkmsServiceKeysType = other.OkmsServiceKeysType
	}

	if (v.state == attr.ValueStateUnknown || v.state == attr.ValueStateNull) && other.state != attr.ValueStateUnknown {
		v.state = other.state
	}
}

func (v OkmsServiceKeysValue) Attributes() map[string]attr.Value {
	return map[string]attr.Value{
		"createdAt":  v.CreatedAt,
		"curve":      v.Curve,
		"id":         v.Id,
		"keys":       v.Keys,
		"name":       v.Name,
		"operations": v.Operations,
		"size":       v.Size,
		"state":      v.State,
		"type":       v.OkmsServiceKeysType,
	}
}
func (v OkmsServiceKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["curve"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["keys"] = basetypes.ListType{
		ElemType: OkmsServiceKeysKeysValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["operations"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["size"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Curve.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["curve"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Keys.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["keys"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Operations.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["operations"] = val

		val, err = v.Size.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.OkmsServiceKeysType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OkmsServiceKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OkmsServiceKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OkmsServiceKeysValue) String() string {
	return "OkmsServiceKeysValue"
}

func (v OkmsServiceKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"created_at": ovhtypes.TfStringType{},
			"curve":      ovhtypes.TfStringType{},
			"id":         ovhtypes.TfStringType{},
			"keys":       ovhtypes.NewTfListNestedType[OkmsServiceKeysKeysValue](ctx),
			"name":       ovhtypes.TfStringType{},
			"operations": ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
			"size":       ovhtypes.TfInt64Type{},
			"state":      ovhtypes.TfStringType{},
			"type":       ovhtypes.TfStringType{},
		},
		map[string]attr.Value{
			"created_at": v.CreatedAt,
			"curve":      v.Curve,
			"id":         v.Id,
			"keys":       v.Keys,
			"name":       v.Name,
			"operations": v.Operations,
			"size":       v.Size,
			"state":      v.State,
			"type":       v.OkmsServiceKeysType,
		})

	return objVal, diags
}

func (v OkmsServiceKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(OkmsServiceKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Curve.Equal(other.Curve) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Keys.Equal(other.Keys) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Operations.Equal(other.Operations) {
		return false
	}

	if !v.Size.Equal(other.Size) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.OkmsServiceKeysType.Equal(other.OkmsServiceKeysType) {
		return false
	}

	return true
}

func (v OkmsServiceKeysValue) Type(ctx context.Context) attr.Type {
	return OkmsServiceKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OkmsServiceKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at": ovhtypes.TfStringType{},
		"curve":      ovhtypes.TfStringType{},
		"id":         ovhtypes.TfStringType{},
		"keys":       ovhtypes.NewTfListNestedType[OkmsServiceKeysKeysValue](ctx),
		"name":       ovhtypes.TfStringType{},
		"operations": ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
		"size":       ovhtypes.TfInt64Type{},
		"state":      ovhtypes.TfStringType{},
		"type":       ovhtypes.TfStringType{},
	}
}

var _ basetypes.ObjectTypable = OkmsServiceKeysKeysType{}

type OkmsServiceKeysKeysType struct {
	basetypes.ObjectType
}

func (t OkmsServiceKeysKeysType) Equal(o attr.Type) bool {
	other, ok := o.(OkmsServiceKeysKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OkmsServiceKeysKeysType) String() string {
	return "OkmsServiceKeysKeysType"
}

func (t OkmsServiceKeysKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	algAttribute, ok := attributes["alg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alg is missing from object`)

		return nil, diags
	}

	algVal, ok := algAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alg expected to be ovhtypes.TfStringValue, was: %T`, algAttribute))
	}

	crvAttribute, ok := attributes["crv"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`crv is missing from object`)

		return nil, diags
	}

	crvVal, ok := crvAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`crv expected to be ovhtypes.TfStringValue, was: %T`, crvAttribute))
	}

	dAttribute, ok := attributes["d"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`d is missing from object`)

		return nil, diags
	}

	dVal, ok := dAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`d expected to be ovhtypes.TfStringValue, was: %T`, dAttribute))
	}

	dpAttribute, ok := attributes["dp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dp is missing from object`)

		return nil, diags
	}

	dpVal, ok := dpAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dp expected to be ovhtypes.TfStringValue, was: %T`, dpAttribute))
	}

	dqAttribute, ok := attributes["dq"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dq is missing from object`)

		return nil, diags
	}

	dqVal, ok := dqAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dq expected to be ovhtypes.TfStringValue, was: %T`, dqAttribute))
	}

	eAttribute, ok := attributes["e"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`e is missing from object`)

		return nil, diags
	}

	eVal, ok := eAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`e expected to be ovhtypes.TfStringValue, was: %T`, eAttribute))
	}

	kAttribute, ok := attributes["k"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`k is missing from object`)

		return nil, diags
	}

	kVal, ok := kAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`k expected to be ovhtypes.TfStringValue, was: %T`, kAttribute))
	}

	keyOpsAttribute, ok := attributes["key_ops"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_ops is missing from object`)

		return nil, diags
	}

	keyOpsVal, ok := keyOpsAttribute.(ovhtypes.TfListNestedValue[ovhtypes.TfStringValue])

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_ops expected to be ovhtypes.TfListNestedValue[ovhtypes.TfStringValue], was: %T`, keyOpsAttribute))
	}

	kidAttribute, ok := attributes["kid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kid is missing from object`)

		return nil, diags
	}

	kidVal, ok := kidAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kid expected to be ovhtypes.TfStringValue, was: %T`, kidAttribute))
	}

	ktyAttribute, ok := attributes["kty"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kty is missing from object`)

		return nil, diags
	}

	ktyVal, ok := ktyAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kty expected to be ovhtypes.TfStringValue, was: %T`, ktyAttribute))
	}

	nAttribute, ok := attributes["n"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`n is missing from object`)

		return nil, diags
	}

	nVal, ok := nAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`n expected to be ovhtypes.TfStringValue, was: %T`, nAttribute))
	}

	pAttribute, ok := attributes["p"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`p is missing from object`)

		return nil, diags
	}

	pVal, ok := pAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`p expected to be ovhtypes.TfStringValue, was: %T`, pAttribute))
	}

	qAttribute, ok := attributes["q"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`q is missing from object`)

		return nil, diags
	}

	qVal, ok := qAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`q expected to be ovhtypes.TfStringValue, was: %T`, qAttribute))
	}

	qiAttribute, ok := attributes["qi"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`qi is missing from object`)

		return nil, diags
	}

	qiVal, ok := qiAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`qi expected to be ovhtypes.TfStringValue, was: %T`, qiAttribute))
	}

	useAttribute, ok := attributes["use"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use is missing from object`)

		return nil, diags
	}

	useVal, ok := useAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use expected to be ovhtypes.TfStringValue, was: %T`, useAttribute))
	}

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return nil, diags
	}

	xVal, ok := xAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be ovhtypes.TfStringValue, was: %T`, xAttribute))
	}

	yAttribute, ok := attributes["y"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`y is missing from object`)

		return nil, diags
	}

	yVal, ok := yAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`y expected to be ovhtypes.TfStringValue, was: %T`, yAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OkmsServiceKeysKeysValue{
		Alg:    algVal,
		Crv:    crvVal,
		D:      dVal,
		Dp:     dpVal,
		Dq:     dqVal,
		E:      eVal,
		K:      kVal,
		KeyOps: keyOpsVal,
		Kid:    kidVal,
		Kty:    ktyVal,
		N:      nVal,
		P:      pVal,
		Q:      qVal,
		Qi:     qiVal,
		Use:    useVal,
		X:      xVal,
		Y:      yVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewOkmsServiceKeysKeysValueNull() OkmsServiceKeysKeysValue {
	return OkmsServiceKeysKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewOkmsServiceKeysKeysValueUnknown() OkmsServiceKeysKeysValue {
	return OkmsServiceKeysKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOkmsServiceKeysKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OkmsServiceKeysKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OkmsServiceKeysKeysValue Attribute Value",
				"While creating a OkmsServiceKeysKeysValue value, a missing attribute value was detected. "+
					"A OkmsServiceKeysKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OkmsServiceKeysKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OkmsServiceKeysKeysValue Attribute Type",
				"While creating a OkmsServiceKeysKeysValue value, an invalid attribute value was detected. "+
					"A OkmsServiceKeysKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OkmsServiceKeysKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OkmsServiceKeysKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OkmsServiceKeysKeysValue Attribute Value",
				"While creating a OkmsServiceKeysKeysValue value, an extra attribute value was detected. "+
					"A OkmsServiceKeysKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OkmsServiceKeysKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	algAttribute, ok := attributes["alg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alg is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	algVal, ok := algAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alg expected to be ovhtypes.TfStringValue, was: %T`, algAttribute))
	}

	crvAttribute, ok := attributes["crv"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`crv is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	crvVal, ok := crvAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`crv expected to be ovhtypes.TfStringValue, was: %T`, crvAttribute))
	}

	dAttribute, ok := attributes["d"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`d is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	dVal, ok := dAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`d expected to be ovhtypes.TfStringValue, was: %T`, dAttribute))
	}

	dpAttribute, ok := attributes["dp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dp is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	dpVal, ok := dpAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dp expected to be ovhtypes.TfStringValue, was: %T`, dpAttribute))
	}

	dqAttribute, ok := attributes["dq"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dq is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	dqVal, ok := dqAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dq expected to be ovhtypes.TfStringValue, was: %T`, dqAttribute))
	}

	eAttribute, ok := attributes["e"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`e is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	eVal, ok := eAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`e expected to be ovhtypes.TfStringValue, was: %T`, eAttribute))
	}

	kAttribute, ok := attributes["k"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`k is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	kVal, ok := kAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`k expected to be ovhtypes.TfStringValue, was: %T`, kAttribute))
	}

	keyOpsAttribute, ok := attributes["key_ops"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_ops is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	keyOpsVal, ok := keyOpsAttribute.(ovhtypes.TfListNestedValue[ovhtypes.TfStringValue])

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_ops expected to be ovhtypes.TfListNestedValue[ovhtypes.TfStringValue], was: %T`, keyOpsAttribute))
	}

	kidAttribute, ok := attributes["kid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kid is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	kidVal, ok := kidAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kid expected to be ovhtypes.TfStringValue, was: %T`, kidAttribute))
	}

	ktyAttribute, ok := attributes["kty"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kty is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	ktyVal, ok := ktyAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kty expected to be ovhtypes.TfStringValue, was: %T`, ktyAttribute))
	}

	nAttribute, ok := attributes["n"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`n is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	nVal, ok := nAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`n expected to be ovhtypes.TfStringValue, was: %T`, nAttribute))
	}

	pAttribute, ok := attributes["p"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`p is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	pVal, ok := pAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`p expected to be ovhtypes.TfStringValue, was: %T`, pAttribute))
	}

	qAttribute, ok := attributes["q"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`q is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	qVal, ok := qAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`q expected to be ovhtypes.TfStringValue, was: %T`, qAttribute))
	}

	qiAttribute, ok := attributes["qi"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`qi is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	qiVal, ok := qiAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`qi expected to be ovhtypes.TfStringValue, was: %T`, qiAttribute))
	}

	useAttribute, ok := attributes["use"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	useVal, ok := useAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use expected to be ovhtypes.TfStringValue, was: %T`, useAttribute))
	}

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	xVal, ok := xAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be ovhtypes.TfStringValue, was: %T`, xAttribute))
	}

	yAttribute, ok := attributes["y"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`y is missing from object`)

		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	yVal, ok := yAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`y expected to be ovhtypes.TfStringValue, was: %T`, yAttribute))
	}

	if diags.HasError() {
		return NewOkmsServiceKeysKeysValueUnknown(), diags
	}

	return OkmsServiceKeysKeysValue{
		Alg:    algVal,
		Crv:    crvVal,
		D:      dVal,
		Dp:     dpVal,
		Dq:     dqVal,
		E:      eVal,
		K:      kVal,
		KeyOps: keyOpsVal,
		Kid:    kidVal,
		Kty:    ktyVal,
		N:      nVal,
		P:      pVal,
		Q:      qVal,
		Qi:     qiVal,
		Use:    useVal,
		X:      xVal,
		Y:      yVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewOkmsServiceKeysKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OkmsServiceKeysKeysValue {
	object, diags := NewOkmsServiceKeysKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOkmsServiceKeysKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OkmsServiceKeysKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOkmsServiceKeysKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOkmsServiceKeysKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOkmsServiceKeysKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOkmsServiceKeysKeysValueMust(OkmsServiceKeysKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OkmsServiceKeysKeysType) ValueType(ctx context.Context) attr.Value {
	return OkmsServiceKeysKeysValue{}
}

var _ basetypes.ObjectValuable = OkmsServiceKeysKeysValue{}

type OkmsServiceKeysKeysValue struct {
	Alg    ovhtypes.TfStringValue                             `tfsdk:"alg" json:"alg"`
	Crv    ovhtypes.TfStringValue                             `tfsdk:"crv" json:"crv"`
	D      ovhtypes.TfStringValue                             `tfsdk:"d" json:"d"`
	Dp     ovhtypes.TfStringValue                             `tfsdk:"dp" json:"dp"`
	Dq     ovhtypes.TfStringValue                             `tfsdk:"dq" json:"dq"`
	E      ovhtypes.TfStringValue                             `tfsdk:"e" json:"e"`
	K      ovhtypes.TfStringValue                             `tfsdk:"k" json:"k"`
	KeyOps ovhtypes.TfListNestedValue[ovhtypes.TfStringValue] `tfsdk:"key_ops" json:"keyOps"`
	Kid    ovhtypes.TfStringValue                             `tfsdk:"kid" json:"kid"`
	Kty    ovhtypes.TfStringValue                             `tfsdk:"kty" json:"kty"`
	N      ovhtypes.TfStringValue                             `tfsdk:"n" json:"n"`
	P      ovhtypes.TfStringValue                             `tfsdk:"p" json:"p"`
	Q      ovhtypes.TfStringValue                             `tfsdk:"q" json:"q"`
	Qi     ovhtypes.TfStringValue                             `tfsdk:"qi" json:"qi"`
	Use    ovhtypes.TfStringValue                             `tfsdk:"use" json:"use"`
	X      ovhtypes.TfStringValue                             `tfsdk:"x" json:"x"`
	Y      ovhtypes.TfStringValue                             `tfsdk:"y" json:"y"`
	state  attr.ValueState
}

func (v *OkmsServiceKeysKeysValue) UnmarshalJSON(data []byte) error {
	type JsonOkmsServiceKeysKeysValue OkmsServiceKeysKeysValue

	var tmp JsonOkmsServiceKeysKeysValue
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}
	v.Alg = tmp.Alg
	v.Crv = tmp.Crv
	v.D = tmp.D
	v.Dp = tmp.Dp
	v.Dq = tmp.Dq
	v.E = tmp.E
	v.K = tmp.K
	v.KeyOps = tmp.KeyOps
	v.Kid = tmp.Kid
	v.Kty = tmp.Kty
	v.N = tmp.N
	v.P = tmp.P
	v.Q = tmp.Q
	v.Qi = tmp.Qi
	v.Use = tmp.Use
	v.X = tmp.X
	v.Y = tmp.Y

	v.state = attr.ValueStateKnown

	return nil
}

func (v *OkmsServiceKeysKeysValue) MergeWith(other *OkmsServiceKeysKeysValue) {

	if (v.Alg.IsUnknown() || v.Alg.IsNull()) && !other.Alg.IsUnknown() {
		v.Alg = other.Alg
	}

	if (v.Crv.IsUnknown() || v.Crv.IsNull()) && !other.Crv.IsUnknown() {
		v.Crv = other.Crv
	}

	if (v.D.IsUnknown() || v.D.IsNull()) && !other.D.IsUnknown() {
		v.D = other.D
	}

	if (v.Dp.IsUnknown() || v.Dp.IsNull()) && !other.Dp.IsUnknown() {
		v.Dp = other.Dp
	}

	if (v.Dq.IsUnknown() || v.Dq.IsNull()) && !other.Dq.IsUnknown() {
		v.Dq = other.Dq
	}

	if (v.E.IsUnknown() || v.E.IsNull()) && !other.E.IsUnknown() {
		v.E = other.E
	}

	if (v.K.IsUnknown() || v.K.IsNull()) && !other.K.IsUnknown() {
		v.K = other.K
	}

	if (v.KeyOps.IsUnknown() || v.KeyOps.IsNull()) && !other.KeyOps.IsUnknown() {
		v.KeyOps = other.KeyOps
	}

	if (v.Kid.IsUnknown() || v.Kid.IsNull()) && !other.Kid.IsUnknown() {
		v.Kid = other.Kid
	}

	if (v.Kty.IsUnknown() || v.Kty.IsNull()) && !other.Kty.IsUnknown() {
		v.Kty = other.Kty
	}

	if (v.N.IsUnknown() || v.N.IsNull()) && !other.N.IsUnknown() {
		v.N = other.N
	}

	if (v.P.IsUnknown() || v.P.IsNull()) && !other.P.IsUnknown() {
		v.P = other.P
	}

	if (v.Q.IsUnknown() || v.Q.IsNull()) && !other.Q.IsUnknown() {
		v.Q = other.Q
	}

	if (v.Qi.IsUnknown() || v.Qi.IsNull()) && !other.Qi.IsUnknown() {
		v.Qi = other.Qi
	}

	if (v.Use.IsUnknown() || v.Use.IsNull()) && !other.Use.IsUnknown() {
		v.Use = other.Use
	}

	if (v.X.IsUnknown() || v.X.IsNull()) && !other.X.IsUnknown() {
		v.X = other.X
	}

	if (v.Y.IsUnknown() || v.Y.IsNull()) && !other.Y.IsUnknown() {
		v.Y = other.Y
	}

	if (v.state == attr.ValueStateUnknown || v.state == attr.ValueStateNull) && other.state != attr.ValueStateUnknown {
		v.state = other.state
	}
}

func (v OkmsServiceKeysKeysValue) Attributes() map[string]attr.Value {
	return map[string]attr.Value{
		"alg":    v.Alg,
		"crv":    v.Crv,
		"d":      v.D,
		"dp":     v.Dp,
		"dq":     v.Dq,
		"e":      v.E,
		"k":      v.K,
		"keyOps": v.KeyOps,
		"kid":    v.Kid,
		"kty":    v.Kty,
		"n":      v.N,
		"p":      v.P,
		"q":      v.Q,
		"qi":     v.Qi,
		"use":    v.Use,
		"x":      v.X,
		"y":      v.Y,
	}
}
func (v OkmsServiceKeysKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 17)

	var val tftypes.Value
	var err error

	attrTypes["alg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["crv"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["d"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dp"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dq"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["e"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["k"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key_ops"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["kid"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kty"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["n"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["p"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["q"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["qi"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["use"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["x"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["y"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 17)

		val, err = v.Alg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alg"] = val

		val, err = v.Crv.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["crv"] = val

		val, err = v.D.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["d"] = val

		val, err = v.Dp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dp"] = val

		val, err = v.Dq.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dq"] = val

		val, err = v.E.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["e"] = val

		val, err = v.K.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["k"] = val

		val, err = v.KeyOps.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_ops"] = val

		val, err = v.Kid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kid"] = val

		val, err = v.Kty.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kty"] = val

		val, err = v.N.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["n"] = val

		val, err = v.P.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["p"] = val

		val, err = v.Q.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["q"] = val

		val, err = v.Qi.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["qi"] = val

		val, err = v.Use.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["use"] = val

		val, err = v.X.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["x"] = val

		val, err = v.Y.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["y"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OkmsServiceKeysKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OkmsServiceKeysKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OkmsServiceKeysKeysValue) String() string {
	return "OkmsServiceKeysKeysValue"
}

func (v OkmsServiceKeysKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"alg":     ovhtypes.TfStringType{},
			"crv":     ovhtypes.TfStringType{},
			"d":       ovhtypes.TfStringType{},
			"dp":      ovhtypes.TfStringType{},
			"dq":      ovhtypes.TfStringType{},
			"e":       ovhtypes.TfStringType{},
			"k":       ovhtypes.TfStringType{},
			"key_ops": ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
			"kid":     ovhtypes.TfStringType{},
			"kty":     ovhtypes.TfStringType{},
			"n":       ovhtypes.TfStringType{},
			"p":       ovhtypes.TfStringType{},
			"q":       ovhtypes.TfStringType{},
			"qi":      ovhtypes.TfStringType{},
			"use":     ovhtypes.TfStringType{},
			"x":       ovhtypes.TfStringType{},
			"y":       ovhtypes.TfStringType{},
		},
		map[string]attr.Value{
			"alg":     v.Alg,
			"crv":     v.Crv,
			"d":       v.D,
			"dp":      v.Dp,
			"dq":      v.Dq,
			"e":       v.E,
			"k":       v.K,
			"key_ops": v.KeyOps,
			"kid":     v.Kid,
			"kty":     v.Kty,
			"n":       v.N,
			"p":       v.P,
			"q":       v.Q,
			"qi":      v.Qi,
			"use":     v.Use,
			"x":       v.X,
			"y":       v.Y,
		})

	return objVal, diags
}

func (v OkmsServiceKeysKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(OkmsServiceKeysKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Alg.Equal(other.Alg) {
		return false
	}

	if !v.Crv.Equal(other.Crv) {
		return false
	}

	if !v.D.Equal(other.D) {
		return false
	}

	if !v.Dp.Equal(other.Dp) {
		return false
	}

	if !v.Dq.Equal(other.Dq) {
		return false
	}

	if !v.E.Equal(other.E) {
		return false
	}

	if !v.K.Equal(other.K) {
		return false
	}

	if !v.KeyOps.Equal(other.KeyOps) {
		return false
	}

	if !v.Kid.Equal(other.Kid) {
		return false
	}

	if !v.Kty.Equal(other.Kty) {
		return false
	}

	if !v.N.Equal(other.N) {
		return false
	}

	if !v.P.Equal(other.P) {
		return false
	}

	if !v.Q.Equal(other.Q) {
		return false
	}

	if !v.Qi.Equal(other.Qi) {
		return false
	}

	if !v.Use.Equal(other.Use) {
		return false
	}

	if !v.X.Equal(other.X) {
		return false
	}

	if !v.Y.Equal(other.Y) {
		return false
	}

	return true
}

func (v OkmsServiceKeysKeysValue) Type(ctx context.Context) attr.Type {
	return OkmsServiceKeysKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OkmsServiceKeysKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alg":     ovhtypes.TfStringType{},
		"crv":     ovhtypes.TfStringType{},
		"d":       ovhtypes.TfStringType{},
		"dp":      ovhtypes.TfStringType{},
		"dq":      ovhtypes.TfStringType{},
		"e":       ovhtypes.TfStringType{},
		"k":       ovhtypes.TfStringType{},
		"key_ops": ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
		"kid":     ovhtypes.TfStringType{},
		"kty":     ovhtypes.TfStringType{},
		"n":       ovhtypes.TfStringType{},
		"p":       ovhtypes.TfStringType{},
		"q":       ovhtypes.TfStringType{},
		"qi":      ovhtypes.TfStringType{},
		"use":     ovhtypes.TfStringType{},
		"x":       ovhtypes.TfStringType{},
		"y":       ovhtypes.TfStringType{},
	}
}
