// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ovh

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	ovhtypes "github.com/ovh/terraform-provider-ovh/ovh/types"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OkmsServiceKeyDataSourceSchema(ctx context.Context) schema.Schema {
	attrs := map[string]schema.Attribute{
		"created_at": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Creation time of the key",
			MarkdownDescription: "Creation time of the key",
		},
		"curve": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Curve type for Elliptic Curve (EC) keys",
			MarkdownDescription: "Curve type for Elliptic Curve (EC) keys",
		},
		"format": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Optional additional output format of the key",
			MarkdownDescription: "Optional additional output format of the key",
			Validators: []validator.String{
				stringvalidator.OneOf(
					"JWK",
				),
			},
		},
		"id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Key ID",
			MarkdownDescription: "Key ID",
		},
		"key_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Key ID",
			MarkdownDescription: "Key ID",
		},
		"keys": schema.ListNestedAttribute{
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"alg": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "The algorithm intended to be used with the key",
						MarkdownDescription: "The algorithm intended to be used with the key",
					},
					"crv": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "The cryptographic curve used with the key",
						MarkdownDescription: "The cryptographic curve used with the key",
					},
					"d": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Sensitive:           true,
						Description:         "The RSA or EC private exponent",
						MarkdownDescription: "The RSA or EC private exponent",
					},
					"dp": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Sensitive:           true,
						Description:         "The RSA private key's first factor CRT exponent",
						MarkdownDescription: "The RSA private key's first factor CRT exponent",
					},
					"dq": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Sensitive:           true,
						Description:         "The RSA private key's second factor CRT exponent",
						MarkdownDescription: "The RSA private key's second factor CRT exponent",
					},
					"e": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "The exponent value for the RSA public key",
						MarkdownDescription: "The exponent value for the RSA public key",
					},
					"k": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Sensitive:           true,
						Description:         "The value of the symmetric (or other single-valued) key",
						MarkdownDescription: "The value of the symmetric (or other single-valued) key",
					},
					"key_ops": schema.ListAttribute{
						CustomType:          ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
						Computed:            true,
						Description:         "The operation for which the key is intended to be used",
						MarkdownDescription: "The operation for which the key is intended to be used",
					},
					"kid": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "key ID parameter used to match a specific key",
						MarkdownDescription: "key ID parameter used to match a specific key",
					},
					"kty": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "Key type parameter identifies the cryptographic algorithm family used with the key, such as RSA or EC",
						MarkdownDescription: "Key type parameter identifies the cryptographic algorithm family used with the key, such as RSA or EC",
					},
					"n": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "The modulus value for the RSA public key",
						MarkdownDescription: "The modulus value for the RSA public key",
					},
					"p": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Sensitive:           true,
						Description:         "The first prime factor of the RSA private key",
						MarkdownDescription: "The first prime factor of the RSA private key",
					},
					"q": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Sensitive:           true,
						Description:         "The second prime factor of the RSA private key",
						MarkdownDescription: "The second prime factor of the RSA private key",
					},
					"qi": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Sensitive:           true,
						Description:         "The CRT coefficient of the second factor of the RSA private key",
						MarkdownDescription: "The CRT coefficient of the second factor of the RSA private key",
					},
					"use": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "The intended use of the public key",
						MarkdownDescription: "The intended use of the public key",
					},
					"x": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "The x coordinate for the Elliptic Curve point",
						MarkdownDescription: "The x coordinate for the Elliptic Curve point",
					},
					"y": schema.StringAttribute{
						CustomType:          ovhtypes.TfStringType{},
						Computed:            true,
						Description:         "The y coordinate for the Elliptic Curve point",
						MarkdownDescription: "The y coordinate for the Elliptic Curve point",
					},
				},
				CustomType: KeysType{
					ObjectType: types.ObjectType{
						AttrTypes: KeysValue{}.AttributeTypes(ctx),
					},
				},
			},
			CustomType:          ovhtypes.NewTfListNestedType[KeysValue](ctx),
			Computed:            true,
			Description:         "The key in JWK format",
			MarkdownDescription: "The key in JWK format",
		},
		"name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Key name",
			MarkdownDescription: "Key name",
		},
		"okms_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Okms ID",
			MarkdownDescription: "Okms ID",
		},
		"operations": schema.ListAttribute{
			CustomType:          ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
			Computed:            true,
			Description:         "The operations for which the key is intended to be used",
			MarkdownDescription: "The operations for which the key is intended to be used",
		},
		"size": schema.Int64Attribute{
			CustomType:          ovhtypes.TfInt64Type{},
			Computed:            true,
			Description:         "Size of the key",
			MarkdownDescription: "Size of the key",
		},
		"state": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "State of the key",
			MarkdownDescription: "State of the key",
		},
		"type": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Key type",
			MarkdownDescription: "Key type",
		},
	}

	return schema.Schema{
		Attributes: attrs,
	}
}

type OkmsServiceKeyModel struct {
	CreatedAt  ovhtypes.TfStringValue                             `tfsdk:"created_at" json:"createdAt"`
	Curve      ovhtypes.TfStringValue                             `tfsdk:"curve" json:"curve"`
	Format     ovhtypes.TfStringValue                             `tfsdk:"format" json:"format"`
	Id         ovhtypes.TfStringValue                             `tfsdk:"id" json:"id"`
	KeyId      ovhtypes.TfStringValue                             `tfsdk:"key_id" json:"keyId"`
	Keys       ovhtypes.TfListNestedValue[KeysValue]              `tfsdk:"keys" json:"keys"`
	Name       ovhtypes.TfStringValue                             `tfsdk:"name" json:"name"`
	OkmsId     ovhtypes.TfStringValue                             `tfsdk:"okms_id" json:"okmsId"`
	Operations ovhtypes.TfListNestedValue[ovhtypes.TfStringValue] `tfsdk:"operations" json:"operations"`
	Size       ovhtypes.TfInt64Value                              `tfsdk:"size" json:"size"`
	State      ovhtypes.TfStringValue                             `tfsdk:"state" json:"state"`
	Type       ovhtypes.TfStringValue                             `tfsdk:"type" json:"type"`
}

func (v *OkmsServiceKeyModel) MergeWith(other *OkmsServiceKeyModel) {

	if (v.CreatedAt.IsUnknown() || v.CreatedAt.IsNull()) && !other.CreatedAt.IsUnknown() {
		v.CreatedAt = other.CreatedAt
	}

	if (v.Curve.IsUnknown() || v.Curve.IsNull()) && !other.Curve.IsUnknown() {
		v.Curve = other.Curve
	}

	if (v.Format.IsUnknown() || v.Format.IsNull()) && !other.Format.IsUnknown() {
		v.Format = other.Format
	}

	if (v.Id.IsUnknown() || v.Id.IsNull()) && !other.Id.IsUnknown() {
		v.Id = other.Id
	}

	if (v.KeyId.IsUnknown() || v.KeyId.IsNull()) && !other.KeyId.IsUnknown() {
		v.KeyId = other.KeyId
	}

	if (v.Keys.IsUnknown() || v.Keys.IsNull()) && !other.Keys.IsUnknown() {
		v.Keys = other.Keys
	}

	if (v.Name.IsUnknown() || v.Name.IsNull()) && !other.Name.IsUnknown() {
		v.Name = other.Name
	}

	if (v.OkmsId.IsUnknown() || v.OkmsId.IsNull()) && !other.OkmsId.IsUnknown() {
		v.OkmsId = other.OkmsId
	}

	if (v.Operations.IsUnknown() || v.Operations.IsNull()) && !other.Operations.IsUnknown() {
		v.Operations = other.Operations
	}

	if (v.Size.IsUnknown() || v.Size.IsNull()) && !other.Size.IsUnknown() {
		v.Size = other.Size
	}

	if (v.State.IsUnknown() || v.State.IsNull()) && !other.State.IsUnknown() {
		v.State = other.State
	}

	if (v.Type.IsUnknown() || v.Type.IsNull()) && !other.Type.IsUnknown() {
		v.Type = other.Type
	}

}

var _ basetypes.ObjectTypable = KeysType{}

type KeysType struct {
	basetypes.ObjectType
}

func (t KeysType) Equal(o attr.Type) bool {
	other, ok := o.(KeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t KeysType) String() string {
	return "KeysType"
}

func (t KeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	algAttribute, ok := attributes["alg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alg is missing from object`)

		return nil, diags
	}

	algVal, ok := algAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alg expected to be ovhtypes.TfStringValue, was: %T`, algAttribute))
	}

	crvAttribute, ok := attributes["crv"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`crv is missing from object`)

		return nil, diags
	}

	crvVal, ok := crvAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`crv expected to be ovhtypes.TfStringValue, was: %T`, crvAttribute))
	}

	dAttribute, ok := attributes["d"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`d is missing from object`)

		return nil, diags
	}

	dVal, ok := dAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`d expected to be ovhtypes.TfStringValue, was: %T`, dAttribute))
	}

	dpAttribute, ok := attributes["dp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dp is missing from object`)

		return nil, diags
	}

	dpVal, ok := dpAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dp expected to be ovhtypes.TfStringValue, was: %T`, dpAttribute))
	}

	dqAttribute, ok := attributes["dq"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dq is missing from object`)

		return nil, diags
	}

	dqVal, ok := dqAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dq expected to be ovhtypes.TfStringValue, was: %T`, dqAttribute))
	}

	eAttribute, ok := attributes["e"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`e is missing from object`)

		return nil, diags
	}

	eVal, ok := eAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`e expected to be ovhtypes.TfStringValue, was: %T`, eAttribute))
	}

	kAttribute, ok := attributes["k"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`k is missing from object`)

		return nil, diags
	}

	kVal, ok := kAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`k expected to be ovhtypes.TfStringValue, was: %T`, kAttribute))
	}

	keyOpsAttribute, ok := attributes["key_ops"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_ops is missing from object`)

		return nil, diags
	}

	keyOpsVal, ok := keyOpsAttribute.(ovhtypes.TfListNestedValue[ovhtypes.TfStringValue])

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_ops expected to be ovhtypes.TfListNestedValue[ovhtypes.TfStringValue], was: %T`, keyOpsAttribute))
	}

	kidAttribute, ok := attributes["kid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kid is missing from object`)

		return nil, diags
	}

	kidVal, ok := kidAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kid expected to be ovhtypes.TfStringValue, was: %T`, kidAttribute))
	}

	ktyAttribute, ok := attributes["kty"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kty is missing from object`)

		return nil, diags
	}

	ktyVal, ok := ktyAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kty expected to be ovhtypes.TfStringValue, was: %T`, ktyAttribute))
	}

	nAttribute, ok := attributes["n"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`n is missing from object`)

		return nil, diags
	}

	nVal, ok := nAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`n expected to be ovhtypes.TfStringValue, was: %T`, nAttribute))
	}

	pAttribute, ok := attributes["p"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`p is missing from object`)

		return nil, diags
	}

	pVal, ok := pAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`p expected to be ovhtypes.TfStringValue, was: %T`, pAttribute))
	}

	qAttribute, ok := attributes["q"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`q is missing from object`)

		return nil, diags
	}

	qVal, ok := qAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`q expected to be ovhtypes.TfStringValue, was: %T`, qAttribute))
	}

	qiAttribute, ok := attributes["qi"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`qi is missing from object`)

		return nil, diags
	}

	qiVal, ok := qiAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`qi expected to be ovhtypes.TfStringValue, was: %T`, qiAttribute))
	}

	useAttribute, ok := attributes["use"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use is missing from object`)

		return nil, diags
	}

	useVal, ok := useAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use expected to be ovhtypes.TfStringValue, was: %T`, useAttribute))
	}

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return nil, diags
	}

	xVal, ok := xAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be ovhtypes.TfStringValue, was: %T`, xAttribute))
	}

	yAttribute, ok := attributes["y"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`y is missing from object`)

		return nil, diags
	}

	yVal, ok := yAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`y expected to be ovhtypes.TfStringValue, was: %T`, yAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return KeysValue{
		Alg:    algVal,
		Crv:    crvVal,
		D:      dVal,
		Dp:     dpVal,
		Dq:     dqVal,
		E:      eVal,
		K:      kVal,
		KeyOps: keyOpsVal,
		Kid:    kidVal,
		Kty:    ktyVal,
		N:      nVal,
		P:      pVal,
		Q:      qVal,
		Qi:     qiVal,
		Use:    useVal,
		X:      xVal,
		Y:      yVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewKeysValueNull() KeysValue {
	return KeysValue{
		state: attr.ValueStateNull,
	}
}

func NewKeysValueUnknown() KeysValue {
	return KeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (KeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing KeysValue Attribute Value",
				"While creating a KeysValue value, a missing attribute value was detected. "+
					"A KeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid KeysValue Attribute Type",
				"While creating a KeysValue value, an invalid attribute value was detected. "+
					"A KeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("KeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra KeysValue Attribute Value",
				"While creating a KeysValue value, an extra attribute value was detected. "+
					"A KeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra KeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	algAttribute, ok := attributes["alg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alg is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	algVal, ok := algAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alg expected to be ovhtypes.TfStringValue, was: %T`, algAttribute))
	}

	crvAttribute, ok := attributes["crv"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`crv is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	crvVal, ok := crvAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`crv expected to be ovhtypes.TfStringValue, was: %T`, crvAttribute))
	}

	dAttribute, ok := attributes["d"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`d is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	dVal, ok := dAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`d expected to be ovhtypes.TfStringValue, was: %T`, dAttribute))
	}

	dpAttribute, ok := attributes["dp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dp is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	dpVal, ok := dpAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dp expected to be ovhtypes.TfStringValue, was: %T`, dpAttribute))
	}

	dqAttribute, ok := attributes["dq"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dq is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	dqVal, ok := dqAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dq expected to be ovhtypes.TfStringValue, was: %T`, dqAttribute))
	}

	eAttribute, ok := attributes["e"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`e is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	eVal, ok := eAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`e expected to be ovhtypes.TfStringValue, was: %T`, eAttribute))
	}

	kAttribute, ok := attributes["k"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`k is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	kVal, ok := kAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`k expected to be ovhtypes.TfStringValue, was: %T`, kAttribute))
	}

	keyOpsAttribute, ok := attributes["key_ops"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_ops is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	keyOpsVal, ok := keyOpsAttribute.(ovhtypes.TfListNestedValue[ovhtypes.TfStringValue])

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_ops expected to be ovhtypes.TfListNestedValue[ovhtypes.TfStringValue], was: %T`, keyOpsAttribute))
	}

	kidAttribute, ok := attributes["kid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kid is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	kidVal, ok := kidAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kid expected to be ovhtypes.TfStringValue, was: %T`, kidAttribute))
	}

	ktyAttribute, ok := attributes["kty"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kty is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	ktyVal, ok := ktyAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kty expected to be ovhtypes.TfStringValue, was: %T`, ktyAttribute))
	}

	nAttribute, ok := attributes["n"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`n is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	nVal, ok := nAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`n expected to be ovhtypes.TfStringValue, was: %T`, nAttribute))
	}

	pAttribute, ok := attributes["p"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`p is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	pVal, ok := pAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`p expected to be ovhtypes.TfStringValue, was: %T`, pAttribute))
	}

	qAttribute, ok := attributes["q"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`q is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	qVal, ok := qAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`q expected to be ovhtypes.TfStringValue, was: %T`, qAttribute))
	}

	qiAttribute, ok := attributes["qi"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`qi is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	qiVal, ok := qiAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`qi expected to be ovhtypes.TfStringValue, was: %T`, qiAttribute))
	}

	useAttribute, ok := attributes["use"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	useVal, ok := useAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use expected to be ovhtypes.TfStringValue, was: %T`, useAttribute))
	}

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	xVal, ok := xAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be ovhtypes.TfStringValue, was: %T`, xAttribute))
	}

	yAttribute, ok := attributes["y"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`y is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	yVal, ok := yAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`y expected to be ovhtypes.TfStringValue, was: %T`, yAttribute))
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	return KeysValue{
		Alg:    algVal,
		Crv:    crvVal,
		D:      dVal,
		Dp:     dpVal,
		Dq:     dqVal,
		E:      eVal,
		K:      kVal,
		KeyOps: keyOpsVal,
		Kid:    kidVal,
		Kty:    ktyVal,
		N:      nVal,
		P:      pVal,
		Q:      qVal,
		Qi:     qiVal,
		Use:    useVal,
		X:      xVal,
		Y:      yVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) KeysValue {
	object, diags := NewKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t KeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewKeysValueMust(KeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t KeysType) ValueType(ctx context.Context) attr.Value {
	return KeysValue{}
}

var _ basetypes.ObjectValuable = KeysValue{}

type KeysValue struct {
	Alg    ovhtypes.TfStringValue                             `tfsdk:"alg" json:"alg"`
	Crv    ovhtypes.TfStringValue                             `tfsdk:"crv" json:"crv"`
	D      ovhtypes.TfStringValue                             `tfsdk:"d" json:"d"`
	Dp     ovhtypes.TfStringValue                             `tfsdk:"dp" json:"dp"`
	Dq     ovhtypes.TfStringValue                             `tfsdk:"dq" json:"dq"`
	E      ovhtypes.TfStringValue                             `tfsdk:"e" json:"e"`
	K      ovhtypes.TfStringValue                             `tfsdk:"k" json:"k"`
	KeyOps ovhtypes.TfListNestedValue[ovhtypes.TfStringValue] `tfsdk:"key_ops" json:"keyOps"`
	Kid    ovhtypes.TfStringValue                             `tfsdk:"kid" json:"kid"`
	Kty    ovhtypes.TfStringValue                             `tfsdk:"kty" json:"kty"`
	N      ovhtypes.TfStringValue                             `tfsdk:"n" json:"n"`
	P      ovhtypes.TfStringValue                             `tfsdk:"p" json:"p"`
	Q      ovhtypes.TfStringValue                             `tfsdk:"q" json:"q"`
	Qi     ovhtypes.TfStringValue                             `tfsdk:"qi" json:"qi"`
	Use    ovhtypes.TfStringValue                             `tfsdk:"use" json:"use"`
	X      ovhtypes.TfStringValue                             `tfsdk:"x" json:"x"`
	Y      ovhtypes.TfStringValue                             `tfsdk:"y" json:"y"`
	state  attr.ValueState
}

func (v *KeysValue) UnmarshalJSON(data []byte) error {
	type JsonKeysValue KeysValue

	var tmp JsonKeysValue
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}
	v.Alg = tmp.Alg
	v.Crv = tmp.Crv
	v.D = tmp.D
	v.Dp = tmp.Dp
	v.Dq = tmp.Dq
	v.E = tmp.E
	v.K = tmp.K
	v.KeyOps = tmp.KeyOps
	v.Kid = tmp.Kid
	v.Kty = tmp.Kty
	v.N = tmp.N
	v.P = tmp.P
	v.Q = tmp.Q
	v.Qi = tmp.Qi
	v.Use = tmp.Use
	v.X = tmp.X
	v.Y = tmp.Y

	v.state = attr.ValueStateKnown

	return nil
}

func (v *KeysValue) MergeWith(other *KeysValue) {

	if (v.Alg.IsUnknown() || v.Alg.IsNull()) && !other.Alg.IsUnknown() {
		v.Alg = other.Alg
	}

	if (v.Crv.IsUnknown() || v.Crv.IsNull()) && !other.Crv.IsUnknown() {
		v.Crv = other.Crv
	}

	if (v.D.IsUnknown() || v.D.IsNull()) && !other.D.IsUnknown() {
		v.D = other.D
	}

	if (v.Dp.IsUnknown() || v.Dp.IsNull()) && !other.Dp.IsUnknown() {
		v.Dp = other.Dp
	}

	if (v.Dq.IsUnknown() || v.Dq.IsNull()) && !other.Dq.IsUnknown() {
		v.Dq = other.Dq
	}

	if (v.E.IsUnknown() || v.E.IsNull()) && !other.E.IsUnknown() {
		v.E = other.E
	}

	if (v.K.IsUnknown() || v.K.IsNull()) && !other.K.IsUnknown() {
		v.K = other.K
	}

	if (v.KeyOps.IsUnknown() || v.KeyOps.IsNull()) && !other.KeyOps.IsUnknown() {
		v.KeyOps = other.KeyOps
	}

	if (v.Kid.IsUnknown() || v.Kid.IsNull()) && !other.Kid.IsUnknown() {
		v.Kid = other.Kid
	}

	if (v.Kty.IsUnknown() || v.Kty.IsNull()) && !other.Kty.IsUnknown() {
		v.Kty = other.Kty
	}

	if (v.N.IsUnknown() || v.N.IsNull()) && !other.N.IsUnknown() {
		v.N = other.N
	}

	if (v.P.IsUnknown() || v.P.IsNull()) && !other.P.IsUnknown() {
		v.P = other.P
	}

	if (v.Q.IsUnknown() || v.Q.IsNull()) && !other.Q.IsUnknown() {
		v.Q = other.Q
	}

	if (v.Qi.IsUnknown() || v.Qi.IsNull()) && !other.Qi.IsUnknown() {
		v.Qi = other.Qi
	}

	if (v.Use.IsUnknown() || v.Use.IsNull()) && !other.Use.IsUnknown() {
		v.Use = other.Use
	}

	if (v.X.IsUnknown() || v.X.IsNull()) && !other.X.IsUnknown() {
		v.X = other.X
	}

	if (v.Y.IsUnknown() || v.Y.IsNull()) && !other.Y.IsUnknown() {
		v.Y = other.Y
	}

	if (v.state == attr.ValueStateUnknown || v.state == attr.ValueStateNull) && other.state != attr.ValueStateUnknown {
		v.state = other.state
	}
}

func (v KeysValue) Attributes() map[string]attr.Value {
	return map[string]attr.Value{
		"alg":    v.Alg,
		"crv":    v.Crv,
		"d":      v.D,
		"dp":     v.Dp,
		"dq":     v.Dq,
		"e":      v.E,
		"k":      v.K,
		"keyOps": v.KeyOps,
		"kid":    v.Kid,
		"kty":    v.Kty,
		"n":      v.N,
		"p":      v.P,
		"q":      v.Q,
		"qi":     v.Qi,
		"use":    v.Use,
		"x":      v.X,
		"y":      v.Y,
	}
}
func (v KeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 17)

	var val tftypes.Value
	var err error

	attrTypes["alg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["crv"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["d"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dp"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["dq"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["e"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["k"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key_ops"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["kid"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kty"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["n"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["p"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["q"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["qi"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["use"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["x"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["y"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 17)

		val, err = v.Alg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alg"] = val

		val, err = v.Crv.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["crv"] = val

		val, err = v.D.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["d"] = val

		val, err = v.Dp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dp"] = val

		val, err = v.Dq.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dq"] = val

		val, err = v.E.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["e"] = val

		val, err = v.K.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["k"] = val

		val, err = v.KeyOps.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_ops"] = val

		val, err = v.Kid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kid"] = val

		val, err = v.Kty.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kty"] = val

		val, err = v.N.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["n"] = val

		val, err = v.P.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["p"] = val

		val, err = v.Q.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["q"] = val

		val, err = v.Qi.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["qi"] = val

		val, err = v.Use.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["use"] = val

		val, err = v.X.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["x"] = val

		val, err = v.Y.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["y"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v KeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v KeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v KeysValue) String() string {
	return "KeysValue"
}

func (v KeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"alg":     ovhtypes.TfStringType{},
			"crv":     ovhtypes.TfStringType{},
			"d":       ovhtypes.TfStringType{},
			"dp":      ovhtypes.TfStringType{},
			"dq":      ovhtypes.TfStringType{},
			"e":       ovhtypes.TfStringType{},
			"k":       ovhtypes.TfStringType{},
			"key_ops": ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
			"kid":     ovhtypes.TfStringType{},
			"kty":     ovhtypes.TfStringType{},
			"n":       ovhtypes.TfStringType{},
			"p":       ovhtypes.TfStringType{},
			"q":       ovhtypes.TfStringType{},
			"qi":      ovhtypes.TfStringType{},
			"use":     ovhtypes.TfStringType{},
			"x":       ovhtypes.TfStringType{},
			"y":       ovhtypes.TfStringType{},
		},
		map[string]attr.Value{
			"alg":     v.Alg,
			"crv":     v.Crv,
			"d":       v.D,
			"dp":      v.Dp,
			"dq":      v.Dq,
			"e":       v.E,
			"k":       v.K,
			"key_ops": v.KeyOps,
			"kid":     v.Kid,
			"kty":     v.Kty,
			"n":       v.N,
			"p":       v.P,
			"q":       v.Q,
			"qi":      v.Qi,
			"use":     v.Use,
			"x":       v.X,
			"y":       v.Y,
		})

	return objVal, diags
}

func (v KeysValue) Equal(o attr.Value) bool {
	other, ok := o.(KeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Alg.Equal(other.Alg) {
		return false
	}

	if !v.Crv.Equal(other.Crv) {
		return false
	}

	if !v.D.Equal(other.D) {
		return false
	}

	if !v.Dp.Equal(other.Dp) {
		return false
	}

	if !v.Dq.Equal(other.Dq) {
		return false
	}

	if !v.E.Equal(other.E) {
		return false
	}

	if !v.K.Equal(other.K) {
		return false
	}

	if !v.KeyOps.Equal(other.KeyOps) {
		return false
	}

	if !v.Kid.Equal(other.Kid) {
		return false
	}

	if !v.Kty.Equal(other.Kty) {
		return false
	}

	if !v.N.Equal(other.N) {
		return false
	}

	if !v.P.Equal(other.P) {
		return false
	}

	if !v.Q.Equal(other.Q) {
		return false
	}

	if !v.Qi.Equal(other.Qi) {
		return false
	}

	if !v.Use.Equal(other.Use) {
		return false
	}

	if !v.X.Equal(other.X) {
		return false
	}

	if !v.Y.Equal(other.Y) {
		return false
	}

	return true
}

func (v KeysValue) Type(ctx context.Context) attr.Type {
	return KeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v KeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alg":     ovhtypes.TfStringType{},
		"crv":     ovhtypes.TfStringType{},
		"d":       ovhtypes.TfStringType{},
		"dp":      ovhtypes.TfStringType{},
		"dq":      ovhtypes.TfStringType{},
		"e":       ovhtypes.TfStringType{},
		"k":       ovhtypes.TfStringType{},
		"key_ops": ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
		"kid":     ovhtypes.TfStringType{},
		"kty":     ovhtypes.TfStringType{},
		"n":       ovhtypes.TfStringType{},
		"p":       ovhtypes.TfStringType{},
		"q":       ovhtypes.TfStringType{},
		"qi":      ovhtypes.TfStringType{},
		"use":     ovhtypes.TfStringType{},
		"x":       ovhtypes.TfStringType{},
		"y":       ovhtypes.TfStringType{},
	}
}
